name: FluxCD - Verify Kustomizations
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  kustomize-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xvzf - && \
          sudo mv kubeconform /usr/local/bin/kubeconform
      - name: Verify Kustomizations
        run: scripts/validate.sh
